### ISSUE TITLE
function align_mem()

### ISSUE THREAD

**Issue by MansurovB-source** [salvoronis/memAlloc#2]
**head->is_free && head->next->is_free && head+head->capacity == head->next** не учитываешь размер структура.
Я думаю должно быть так **head->is_free && head->next->is_free && head+ sizeof(struct mem) + head->capacity == head->next**. Или можно вообще сбросить часть проверки **head+ sizeof(struct mem) + head->capacity == head->next**

**Comment by salvoronis** [comment]
fixed
